
-- Creating Tables

CREATE TABLE `USER` (
  `UserID` int(11) NOT NULL AUTO_INCREMENT,
  `Fname` varchar(20) NOT NULL,
  `Lname` varchar(20) NOT NULL,
  `Address` varchar(100) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Password` varchar(20) NOT NULL,
  `Admin` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UserID`,`Email`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

CREATE TABLE `STORE` (
  `StoreID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(25) NOT NULL,
  `Address` varchar(30) NOT NULL,
  PRIMARY KEY (`StoreID`)
) ENGINE=InnoDB AUTO_INCREMENT=124 DEFAULT CHARSET=latin1;

CREATE TABLE `INVENTORY` (
  `StoreID` int(11) NOT NULL,
  `Capacity` int(11) NOT NULL,
  PRIMARY KEY (`StoreID`),
  CONSTRAINT `INVENTORY_Store_id` FOREIGN KEY (`StoreID`) REFERENCES `STORE` (`StoreID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ITEM` (
  `ItemID` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `Price` int(11) NOT NULL,
  `Gender` char(1) NOT NULL,
  `Stock` int(11) NOT NULL DEFAULT '0',
  `StoreID` int(11) NOT NULL,
  `SupplierID` int(11) NOT NULL,
  `Image` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ItemID`),
  KEY `ITEM_Store_id` (`StoreID`),
  KEY `ITEM_Supplier_id` (`SupplierID`),
  CONSTRAINT `ITEM_Store_id` FOREIGN KEY (`StoreID`) REFERENCES `STORE` (`StoreID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ITEM_Supplier_id` FOREIGN KEY (`SupplierID`) REFERENCES `SUPPLIER` (`SupplierID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=311 DEFAULT CHARSET=latin1;

CREATE TABLE `SUPPLIER` (
  `SupplierID` int(11) NOT NULL AUTO_INCREMENT,
  `Supplier_Name` varchar(40) NOT NULL,
  `Address` varchar(100) NOT NULL,
  PRIMARY KEY (`SupplierID`),
  UNIQUE KEY `Supplier_Name` (`Supplier_Name`)
) ENGINE=InnoDB AUTO_INCREMENT=328 DEFAULT CHARSET=latin1;

CREATE TABLE `MANAGER` (
  `ManagerID` int(11) NOT NULL,
  `StoreID` int(11) NOT NULL,
  PRIMARY KEY (`ManagerID`),
  KEY `MANAGER_Store_id` (`StoreID`),
  CONSTRAINT `MANAGER_Store_id` FOREIGN KEY (`StoreID`) REFERENCES `STORE` (`StoreID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `MANAGER_User_id` FOREIGN KEY (`ManagerID`) REFERENCES `USER` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `RESTOCKORDER` (
  `OrderID` int(11) NOT NULL AUTO_INCREMENT,
  `Date` varchar(10) NOT NULL,
  `Quantity` int(11) NOT NULL,
  `ItemID` int(11) NOT NULL,
  `SupplierID` int(11) NOT NULL,
  `StoreID` int(11) NOT NULL,
  PRIMARY KEY (`OrderID`),
  KEY `RESTOCK_Store_id` (`StoreID`),
  KEY `RESTOCK_Supplier_id` (`SupplierID`),
  KEY `RESTOCK_Item_id` (`ItemID`),
  CONSTRAINT `RESTOCK_Item_id` FOREIGN KEY (`ItemID`) REFERENCES `ITEM` (`ItemID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `RESTOCK_Store_id` FOREIGN KEY (`StoreID`) REFERENCES `STORE` (`StoreID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `RESTOCK_Supplier_id` FOREIGN KEY (`SupplierID`) REFERENCES `SUPPLIER` (`SupplierID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;

CREATE TABLE `CART` (
  `ItemID` int(11) NOT NULL,
  `UserID` int(11) NOT NULL,
  `Quantity` int(11) NOT NULL,
  PRIMARY KEY (`ItemID`,`UserID`),
  KEY `CART_User_id_idx` (`UserID`),
  CONSTRAINT `CART_Item_id` FOREIGN KEY (`ItemID`) REFERENCES `ITEM` (`ItemID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CART_User_id` FOREIGN KEY (`UserID`) REFERENCES `USER` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TOPS` (
  `ItemID` int(11) NOT NULL,
  `Chest_Size` int(11) NOT NULL,
  `Shirt_Length` int(11) NOT NULL,
  `Type` varchar(8) NOT NULL,
  PRIMARY KEY (`ItemID`),
  CONSTRAINT `TOPS_Item_id` FOREIGN KEY (`ItemID`) REFERENCES `ITEM` (`ItemID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SHOES` (
  `ItemID` int(11) NOT NULL,
  `ShoeSize` int(11) NOT NULL,
  `Type` varchar(15) NOT NULL,
  PRIMARY KEY (`ItemID`),
  CONSTRAINT `SHOES_Item_id` FOREIGN KEY (`ItemID`) REFERENCES `ITEM` (`ItemID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `BOTTOMS` (
  `ItemID` int(11) NOT NULL,
  `Waist_Size` int(11) NOT NULL,
  `Pant_Length` int(11) NOT NULL,
  `Type` varchar(15) NOT NULL,
  PRIMARY KEY (`ItemID`),
  CONSTRAINT `BOTTOMS_Item_id` FOREIGN KEY (`ItemID`) REFERENCES `ITEM` (`ItemID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ACCESSORIES` (
  `ItemID` int(11) NOT NULL,
  `Type` varchar(15) NOT NULL,
  PRIMARY KEY (`ItemID`),
  CONSTRAINT `ACCESSORIES_Item_id` FOREIGN KEY (`ItemID`) REFERENCES `ITEM` (`ItemID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PURCHASE` (
  `PurchaseID` int(11) NOT NULL AUTO_INCREMENT,
  `ItemID` int(11) NOT NULL,
  `UserID` int(11) NOT NULL,
  `DateTime` varchar(10) NOT NULL,
  `Quantity` int(11) NOT NULL,
  PRIMARY KEY (`PurchaseID`),
  KEY `PURCHASE_Item_id_idx` (`ItemID`),
  KEY `PURCHASE_User_id` (`UserID`),
  CONSTRAINT `PURCHASE_Item_id` FOREIGN KEY (`ItemID`) REFERENCES `ITEM` (`ItemID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PURCHASE_User_id` FOREIGN KEY (`UserID`) REFERENCES `USER` (`UserID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;

-- Test Data

INSERT INTO USER VALUES (7, 'Customer', 'One', '123 Test Road', 'c1@gmail.com', 'password', 0);
INSERT INTO USER VALUES (8, 'Manager', 'One', '456 Trail Way', 'm1@gmail.com', 'password', 1);

INSERT INTO STORE VALUES (100, 'Test Store', '789 Store Place');

INSERT INTO SUPPLIER VALUES (500,'Supplier', '1011 Supply Blvd');

INSERT INTO INVENTORY VALUES (100, 1000);

INSERT INTO MANAGER VALUES (8, 100);

INSERT INTO ITEM VALUES (200, 'Shirt', 40, 'M', 180, 100, 500, './tee.jpg');
INSERT INTO ITEM VALUES (201, 'Pants', 90, 'M', 120, 100, 500, './anklePants.jpg');
INSERT INTO ITEM VALUES (202, 'Shoes', 130, 'U', 100, 100, 500, './AF1.jpg');
INSERT INTO ITEM VALUES (203, 'Earrings', 30, 'W', 250, 100, 500, './chanelEarrings.jpg');

INSERT INTO TOPS VALUES (200, 100, 73, 'Shirt');

INSERT INTO BOTTOMS VALUES (201, 29, 28, 'Pants');

INSERT INTO SHOES VALUES(202, 9, 'Sneakers');

INSERT INTO ACCESSORIES VALUES (203, 'Earrings');

INSERT INTO CART VALUES (200, 7, 1);

INSERT INTO PURCHASE VALUES(600, 201, 7, '2019-12-06', 2);

INSERT INTO RESTOCKORDER VALUES(700, '2019-12-06', 90, 203, 500, 100);

